### ISSUE TITLE
Duplicate creation of the monitoring namespace

### ISSUE THREAD

**Issue by sandrieux** [CNA-Tech/Apps-on-PKS#7]
Just before deploying prometheus it is written to create the monitoring namespace, but it was created already earlier.

**Comment by kacole2** [comment]
@sandrieux can you put a link to the code in here?

I'm going to assign @pdaigle to review it as well

**Comment by sandrieux** [comment]
Hi,

Here you are:
https://github.com/CNA-Tech/Apps-on-PKS/tree/master/prometheus <https://github.com/CNA-Tech/Apps-on-PKS/tree/master/prometheus>

Just before the “Prometheus Validation” Chapter. Namespace is already created in the “Certificate Manager” chapter.

Best regards,
Stefan ANDRIEUX
Mobile: +1 617 485 8287

**Comment by kacole2** [comment]
@sandrieux can you specify which line in the code? You can click on the line and drop the link in the comments.

**Comment by kacole2** [comment]
this has been solved with #13
